// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwuebfTV775Hba7WYgbXwMgRUCGLW5z10',
    appId: '1:451374106844:web:da8cb780d3b6027a8c8c19',
    messagingSenderId: '451374106844',
    projectId: 'spacenews-95c44',
    authDomain: 'spacenews-95c44.firebaseapp.com',
    storageBucket: 'spacenews-95c44.firebasestorage.app',
    measurementId: 'G-LG298QWLDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRtRJwZh1FcCe50E23kX1oFGrfC9-83Nc',
    appId: '1:451374106844:android:2fb2645551acdcd28c8c19',
    messagingSenderId: '451374106844',
    projectId: 'spacenews-95c44',
    storageBucket: 'spacenews-95c44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfo7JLPVkRgC0kccufp8CI1Yw6Cd7p41w',
    appId: '1:451374106844:ios:015b0391f3d0f4a58c8c19',
    messagingSenderId: '451374106844',
    projectId: 'spacenews-95c44',
    storageBucket: 'spacenews-95c44.firebasestorage.app',
    iosBundleId: 'com.example.spaceNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfo7JLPVkRgC0kccufp8CI1Yw6Cd7p41w',
    appId: '1:451374106844:ios:015b0391f3d0f4a58c8c19',
    messagingSenderId: '451374106844',
    projectId: 'spacenews-95c44',
    storageBucket: 'spacenews-95c44.firebasestorage.app',
    iosBundleId: 'com.example.spaceNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwuebfTV775Hba7WYgbXwMgRUCGLW5z10',
    appId: '1:451374106844:web:f8a2a270b13b73b18c8c19',
    messagingSenderId: '451374106844',
    projectId: 'spacenews-95c44',
    authDomain: 'spacenews-95c44.firebaseapp.com',
    storageBucket: 'spacenews-95c44.firebasestorage.app',
    measurementId: 'G-6M4TFGV5Y9',
  );
}
